env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
    # disables certain airbnb rules
    max-classes-per-file: 0,
    no-shadow: 0,
    no-unused-vars: 0,
    import/no-unresolved: 0,
    global-require: 0,
    import/extensions: 0,
    no-console: 0,
    import/no-dynamic-require: 0,
    class-methods-use-this: 0,
    import/prefer-default-export: 0,
  }
